baseURL = "https://kristenwomack.github.io/"
languageCode = "en-us"
title = "Kristen Womack"
contentDir = "pages"

[params]
  author = "Kristen Womack"
  description = "Talks, papers, and writing by Kristen Womack"

[outputs]
  home = ["HTML", "RSS"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  talks = "/talks/:year/:month/:slug/"
  papers = "/papers/:year/:month/:slug/"
  blog = "/blog/:year/:month/:slug/"
